### ISSUE TITLE
Mise à jour de la liste des rules

### ISSUE THREAD

**Issue by A-Lvu** [CERT-EDF/generaptor#2]
### Summary

Hello @koromodako, est il envisagé ou possible de rajouter toutes les rules de la target "KapeRules": https://github.com/Velocidex/velociraptor/blob/master/artifacts/definitions/Windows/KapeFiles/Targets.yaml#L1010 dans le fichier des rules windows.rules.csv ?
Merci.

### Basic Example

Compléter la liste des rules existantes (976) avec la liste complète de vélociraptor (1338). 

### Drawbacks

Plus d'artefacts seront présents pour les collectes et la création de targets custom.

**Comment by CERT-EDF-MAINTAINER** [comment]
Hello A-Lvu, 

Merci pour cette question. Il est effectivement envisageable d'intégrer l'intégralité des règles en question (c'est le travail qui a été fait  lors de la création de cet outil). Néanmoins, ces listes sont en évolution constante, le suivi et l'intégration de ces dernières demande du temps.

Dans l'attente de l'intégration des règles manquantes, il est possible d'utiliser le mécanisme de surcharge [documenté dans le README](https://github.com/CERT-EDF/generaptor?tab=readme-ov-file#expert-collector-generation). Ce mécanisme permet d'ajouter des règles spécifiques au besoin de l'utilisateur.

La méthode proposée permet de contourner cette limitation en attendant la prochaine mise à jour des règles.

**Comment by CERT-EDF-MAINTAINER** [comment]
La version [10.0.2](https://github.com/CERT-EDF/generaptor/releases/tag/10.0.2) contient les règles les plus récentes.
