### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by sh1dow3r** [CERT-EDF/generaptor#3]
Refresh is replace with update it looks like 
https://github.com/CERT-EDF/generaptor/blob/9d1c37fda3453a258075a09d24b28039f89eb7d2/README.md?plain=1#L38

**Comment by CERT-EDF-MAINTAINER** [comment]
Publication of version [10.0.2](https://github.com/CERT-EDF/generaptor/releases/tag/10.0.2) fixes this issue
